version: '3.8'
services:
  app:
    restart: always
    build: .
    environment:
      NOTION_REFERENCE_DB: #notion database id
      NOTION_SECRET:
      ANTHROPIC_API_KEY:
      GITHUB_TOKEN:
      GEMINI_API_KEY:
    volumes:
      - ./:/app
